In [1]:
import pandas as pd
df = pd.read_csv("day24_diabetes_dataset.csv")
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,1,89,66,23,94,28.1,0.167,25,0
1,0,110,70,20,85,25.6,0.201,22,0
2,3,145,78,35,180,33.2,0.672,35,1
3,2,126,72,28,110,30.4,0.412,28,0
4,5,168,88,42,250,36.5,0.893,45,1

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               20 non-null     int64
 1   Glucose                   20 non-null     int64
 2   BloodPressure             20 non-null     int64
 3   SkinThickness             20 non-null     int64
 4   Insulin                   20 non-null     int64
 5   BMI                       20 non-null     float64
 6   DiabetesPedigreeFunction  20 non-null     float64
 7   Age                       20 non-null     int64
 8   Outcome                   20 non-null     int64
dtypes: float64(2), int64(7)
memory usage: 1.5 KB

In [4]:
x = df.drop("Outcome",axis=1)
y = df["Outcome"]
x.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,1,89,66,23,94,28.1,0.167,25
1,0,110,70,20,85,25.6,0.201,22
2,3,145,78,35,180,33.2,0.672,35
3,2,126,72,28,110,30.4,0.412,28
4,5,168,88,42,250,36.5,0.893,45

In [5]:
x.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
dtype: int64

In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [8]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

In [9]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [10]:
model.fit(x_train_scaled, y_train)

LogisticRegression()

In [11]:
y_pred = model.predict(x_test_scaled)

In [12]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 1.0

In [13]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)
print(cm)

[[2 0]
 [0 2]]

In [14]:
from sklearn.metrics import precision_score, recall_score, f1_score
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
print("precision_score: ",precision)
print("recall_score: ",recall)
print("f1_score: ",f1)

precision_score:  1.0
recall_score:  1.0
f1_score:  1.0

In [15]:
print(model.coef_)

[[0.36775572 0.52391112 0.46072764 0.53409205 0.51024982 0.57815096
  0.54240118 0.50909243]]

In [16]:
feature_importance = pd.DataFrame({
    "Feature": x.columns,
    "Coefficient": model.coef_[0]
})
print(feature_importance)

                    Feature  Coefficient
0               Pregnancies     0.367756
1                   Glucose     0.523911
2             BloodPressure     0.460728
3             SkinThickness     0.534092
4                   Insulin     0.510250
5                       BMI     0.578151
6  DiabetesPedigreeFunction     0.542401
7                       Age     0.509092

In [18]:
from sklearn.pipeline import Pipeline

pipeline = Pipeline([
    ("scaler", StandardScaler()),
    ("model", LogisticRegression())
])
print(pipeline)

Pipeline(steps=[('scaler', StandardScaler()), ('model', LogisticRegression())])

In [20]:
from sklearn.model_selection import cross_val_score

cv_scores = cross_val_score(
    pipeline,
    x,
    y,
    cv=5,
    scoring="accuracy"
)

print("Cross-validation scores:", cv_scores)
print("Mean CV accuracy:", cv_scores.mean())

Cross-validation scores: [1.   1.   1.   1.   0.75]
Mean CV accuracy: 0.95