In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("titanic.csv")
df.head()
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [3]:
median_age = df["Age"].median()
print(median_age)

28.0

In [4]:
df["Age"] = df["Age"].fillna(median_age)
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [5]:
x = df[["Pclass","Age","Fare"]]
y = df["Survived"]

In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [7]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators=100,random_state=42)
model.fit(x_train,y_train)

RandomForestClassifier(random_state=42)

In [8]:
train_pred = model.predict(x_train)

In [9]:
from sklearn.metrics import accuracy_score
accuracy_calculate = accuracy_score(y_train,train_pred)
print(accuracy_calculate)

0.952247191011236

In [11]:
test_pred = model.predict(x_test)
from sklearn.metrics import accuracy_score
accuracy_test = accuracy_score(y_test,test_pred)
print(accuracy_test)

0.7262569832402235

In [12]:
from sklearn.metrics import accuracy_score
accuracy_test = accuracy_score(y_test,test_pred)
print(accuracy_test)

0.7262569832402235

In [16]:
importance = model.feature_importances_

for feature, score in zip(x.columns, importance):
    print(feature, ":", score)

Pclass : 0.09144449715873891
Age : 0.4044619396598389
Fare : 0.5040935631814222

In [18]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test,test_pred)
print(confusion_matrix)

[[87 18]
 [31 43]]

In [19]:
from sklearn.metrics import classification_report
print(classification_report(y_test, test_pred))

              precision    recall  f1-score   support

           0       0.74      0.83      0.78       105
           1       0.70      0.58      0.64        74

    accuracy                           0.73       179
   macro avg       0.72      0.70      0.71       179
weighted avg       0.72      0.73      0.72       179