In [4]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv("titanic.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [6]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [7]:
median_age = df["Age"].median()
df["Age"] = df["Age"].fillna(median_age)

In [8]:
x = df[["Pclass","Age","Fare"]]
y = df["Survived"]

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [12]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [13]:
from sklearn.svm import SVC

In [14]:
model = SVC(kernel="linear")

In [16]:
model.fit(x_train_scaled, y_train)

SVC(kernel='linear')

In [18]:
train_pred = model.predict(x_train_scaled)

In [19]:
from sklearn.metrics import accuracy_score

train_accuracy = accuracy_score(y_train, train_pred)
print("Training Accuracy:", train_accuracy)

Training Accuracy: 0.6910112359550562

In [22]:
test_pred = model.predict(x_test_scaled)

In [23]:
test_accuracy = accuracy_score(y_test, test_pred)
print("Testing Accuracy:", test_accuracy)

Testing Accuracy: 0.7150837988826816