In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("Housing.csv")

In [3]:
df["mainroad"] = df["mainroad"].map({"yes":1,"no":0})
df["guestroom"] = df["guestroom"].map({"yes":1,"no":0})
df["basement"] = df["basement"].map({"yes":1,"no":0})
df["hotwaterheating"] = df["hotwaterheating"].map({"yes":1,"no":0})
df["airconditioning"] = df["airconditioning"].map({"yes":1,"no":0})
df["prefarea"] = df["prefarea"].map({"yes":1,"no":0})
df["furnishingstatus"] = df["furnishingstatus"].map({"semi-furnished":0,"furnished":1, "unfurnished":2})

In [4]:
df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,1,0,0,0,1,2,1,1
1,12250000,8960,4,4,4,1,0,0,0,1,3,0,1
2,12250000,9960,3,2,2,1,0,1,0,0,2,1,0
3,12215000,7500,4,2,2,1,0,1,0,1,3,1,1
4,11410000,7420,4,1,2,1,1,1,0,1,2,0,1

In [5]:
df.isnull().sum()

price               0
area                0
bedrooms            0
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
dtype: int64

In [6]:
x = df.drop("price",axis=1)
y = df["price"]

In [7]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [8]:
from sklearn.linear_model import LinearRegression

model_lr = LinearRegression()

model_lr.fit(x_train,y_train)

y_pred_lr = model_lr.predict(x_test)

In [9]:
from sklearn.metrics import mean_absolute_error,r2_score
mae = mean_absolute_error(y_test,y_pred_lr)
r2 = r2_score(y_test,y_pred_lr)
print(mae)
print(r2)

956660.380038148
0.6542221839581839

In [12]:
from sklearn.tree import DecisionTreeRegressor

model_dt = DecisionTreeRegressor()

model_dt.fit(x_train, y_train)

y_pred_dt = model_dt.predict(x_test)

In [13]:
from sklearn.metrics import mean_absolute_error,r2_score
mae = mean_absolute_error(y_test,y_pred_dt)
r2 = r2_score(y_test,y_pred_dt)
print(mae)
print(r2)

1252197.2477064221
0.4298869615173495

In [19]:
from sklearn.ensemble import RandomForestRegressor

model_rf = RandomForestRegressor(n_estimators=100, random_state=42)

model_rf.fit(x_train, y_train)

y_pred_rf = model_rf.predict(x_test)

In [20]:
from sklearn.metrics import mean_absolute_error,r2_score
mae = mean_absolute_error(y_test,y_pred_rf)
r2 = r2_score(y_test,y_pred_rf)
print(mae)
print(r2)

1019913.7730886851
0.6127345060405706