In [9]:
import pandas as pd
df = pd.read_csv("Housing.csv")
df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [10]:
df["mainroad"] = df["mainroad"].map({
    "yes":1,
    "no":0
})
df["guestroom"] = df["guestroom"].map({
    "yes":1,
    "no":0
})
df["basement"] = df["basement"].map({
    "yes":1,
    "no":0
})
df["hotwaterheating"] = df["hotwaterheating"].map({
    "yes":1,
    "no":0
})
df["airconditioning"] = df["airconditioning"].map({
    "yes":1,
    "no":0
})
df["prefarea"] = df["prefarea"].map({
    "yes":1,
    "no":0
})
df["furnishingstatus"] = df["furnishingstatus"].map({
    "semi-furnished":0,
    "furnished":1,
    "unfurnished":2
})

In [11]:
df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,1,0,0,0,1,2,1,1
1,12250000,8960,4,4,4,1,0,0,0,1,3,0,1
2,12250000,9960,3,2,2,1,0,1,0,0,2,1,0
3,12215000,7500,4,2,2,1,0,1,0,1,3,1,1
4,11410000,7420,4,1,2,1,1,1,0,1,2,0,1

In [14]:
x = df.drop("price", axis=1)
y = df["price"]

In [15]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2,random_state=42)

In [16]:
from sklearn.tree import DecisionTreeRegressor
model = DecisionTreeRegressor()

In [18]:
model.fit(x_train, y_train)
y_pred = model.predict(x_test)
print(y_pred)

[ 5600000.  7840000.  3850000.  4900000.  2660000.  3500000.  7070000.
  4893000.  2100000.  2940000. 10850000.  2957500.  3255000.  3703000.
  2653000.  4200000.  3447500.  4270000.  3129000.  3710000.  5810000.
  5950000.  2957500.  3633000.  6020000.  6790000.  2870000.  4200000.
  7000000.  2961000.  6615000.  2800000.  6195000.  4270000.  2485000.
  6405000.  4900000.  4200000.  3115000.  3885000.  3773000.  2870000.
  7840000.  4480000.  4270000.  4200000.  7560000.  4480000.  2450000.
  3430000.  8960000.  1855000.  3500000.  4900000.  3500000.  2940000.
  8295000.  2450000.  5040000.  2957500.  3815000.  3430000.  4200000.
  4200000.  4403000.  4550000.  5950000.  2450000.  6265000.  3395000.
  4200000.  5460000.  8400000.  9100000.  3290000.  4025000.  4550000.
  3010000.  3710000.  5600000.  8540000.  4480000.  5250000.  5040000.
  2450000.  5600000.  3465000.  4473000.  9100000. 10150000.  3080000.
  4970000.  3500000.  2940000. 10150000.  4550000.  5600000.  5740000.
  2852500.  5950000.  4473000.  7350000.  3780000.  4767000.  5040000.
  5040000.  7560000.  7210000.  7700000.]

In [19]:
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_test, y_pred)
print(mae)

1210165.1376146788

In [20]:
from sklearn.metrics import r2_score
r2 = r2_score(y_test, y_pred)
print(r2)

0.4625160501645952